_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 41
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 50
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.5
            "5": 0.18.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
dataset:
    value: EGU2024_total_river
epochs:
    value: 3000
learning_rate:
    value: 0.0001
